name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubunut-latest
    steps:
      - 
        name: Login to Docker HUb
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKER }}
      -
        name: Build and push
        uses: docker/build-push-actions@v6
        with:
          platform: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
      
